- src/swagger.json
Signed-off-by: Greg Werner <werner.greg@gmail.com>
#7
> minor ref fixes

- swagger/README.md
- swagger/swagger.json
New version, 0.2.2. Includes refactoring and fixes.
#9
> Generated code by SwaggerHub

- swagger/swagger.json
Creating version 1.1 which changes host url.
> Generated code by SwaggerHub - v1.1

- README.md
- swagger/swagger.json
> Documentation for swagger.json sync

- README.md
Signed-off-by: Greg Werner <werner.greg@gmail.com>
Closes #27
> Add reference to semver.org

- .travis.yml
- config/api-spec_validation_test.sh
- swagger/tbs_swagger.yml
> validate with travis

- tbs_swagger.yml
Removed base path version from auth endpoints.
> Base path fix (#79)

- tbs_swagger.yml
> X headers (#81)

- tbs_swagger.yml
Only updated user examples for right now to make sure that this is what you guys want. Will continue with rest of the API after this is merged.
Fixes #38
> Updated user examples only

- tbs_swagger.yml
Endpoint to validate server key.
> Server auth

- tbs_swagger.yml
Documentation portion of 3blades/app-backend#352 - Soft delete servers
Signed-off-by: John Griebel <jgriebel@3blades.io>
> Remove terminate server endpoint from docs.

- tbs_swagger.yml
> Docs for name lookup

- tbs_swagger.yml
> Revert some changes

- tbs_swagger.yml
> Add InvoiceItems to tbs_swagger.yml

- tbs_swagger.yml
> add the me endpoint.

- tbs_swagger.yml
> Missing / in $ref

- tbs_swagger.yml
> Add spec for notifications

- tbs_swagger.yml
> Add documentation for copying projects.

- tbs_swagger.yml
> Update the docs to reflect the changes.

- tbs_swagger.yml
Per the design of app-back feature https://github.com/3Blades/app-backend/pull/527
Updating the swagger documentation to reflect the changes in the app-backend repo
> Document feature: #180 - Updating swagger to include foreign keys

- tbs_swagger.yml
Docs for 3Blades/app-backend#604
> Server statuses endpoint docs

- tbs_swagger.yml
Closes: 3Blades/app-backend#639
> Remove unnecessary reset api key endpoint
